services:
  postgres_db:
    container_name: postgres_db
    image: postgres:15.1
    volumes:
      #!- postgres-db:/var/lib/postgresql/data #? Uncomment if using a named volume
      - ./postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: 123456

  pgadmin:
    depends_on:
      - postgres_db
    image: dpage/pgadmin4:6.17
    ports:
      - "5050:80"
    volumes:
      - ./pgadmin:/var/lib/pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    
#volumes:
#  postgres-db:
#    #external: true #? Uncomment if using an external volume
#    driver: local #? Uncomment if generating a local volume